spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/moarychan/spring-petclinic-microservices-config
          default-label: fix-outdated-properties
        native:
          search-locations: classpath:.
  profiles:
    active: native
