spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/felipmiguel/spring-petclinic-microservices-config
        native:
          search-locations: classpath:.
        default-label: fix-passwordless
  profiles:
    active: native
